@startuml

skinparam linetype ortho

state Running {
	state "Check inputs" as Check_inputs
	state "Run entity behavior" as Run_entity_behavior

	[*] --> Check_inputs
	Check_inputs --> Run_entity_behavior
	Run_entity_behavior --> [*]
}

[*] --> Running : Run
Running --> Running
Running --> [*] : Aborted

@enduml
